#pragma once

#define KEY_A						0
#define KEY_B						11
#define KEY_C						8
#define KEY_D						2
#define KEY_E						14
#define KEY_F						3
#define KEY_G						5
#define KEY_H						4
#define KEY_I						34
#define KEY_J						38
#define KEY_K						40
#define KEY_L						37
#define KEY_M						46
#define KEY_N						45
#define KEY_O						31
#define KEY_P						35
#define KEY_Q						12
#define KEY_R						15
#define KEY_S						1
#define KEY_T						17
#define KEY_U						32
#define KEY_V						9
#define KEY_W						13
#define KEY_X						7
#define KEY_Y						16
#define KEY_Z						6
#define KEY_SPACE				49
#define KEY_ONE					18
#define KEY_TWO					19
#define KEY_THREE				20
#define KEY_FOUR				21
#define KEY_FIVE				23
#define KEY_SIX					22
#define KEY_SEVEN				26
#define KEY_EIGHT				28
#define KEY_NINE				25
#define KEY_ZERO				29
#define KEY_MINUS				27
#define KEY_EQUALS			24
#define KEY_COMMA				43
#define KEY_DOT					47
#define KEY_FWD_SLASH		44
#define KEY_PARENTHESIS	41
#define KEY_ENTER				36
#define KEY_PARAGRAPH		10
#define KEY_TAB					53
#define ARROW_LEFT			123
#define ARROW_DOWN			125
#define ARROW_RIGHT			124
#define ARROW_UP				126

